- ch.elexis.agenda/src/ch/elexis/actions/AgendaActions.java
> [5873] Gegenwaertig selektierter Status wird nicht als gewaehlt

- ch.elexis.agenda/src/ch/elexis/agenda/data/Termin.java
- ch.elexis.agenda/src/ch/elexis/dialogs/TerminDialog.java
> [5907] Beim Initial-Erstellen eines Termins mit Notfall Flag geht dieses

- ch.elexis.base.ch.arzttarife/src/ch/elexis/tarmed/printer/EZPrinter.java
@huthomas schau dir das bitte noch an, sollte bis morgen mittag erledigt sein.
> [5986] Gesetzlicher Vertreter bei Tarmedrechnung_EZ (#54)

- ch.elexis.base.befunde/src/ch/elexis/base/befunde/EditFindingDialog.java
> [6751] NPE beim Erstellen von neuem Röntgen-Eintrag in Perspektive

- at.medevit.elexis.ehc.ui/src/at/medevit/elexis/ehc/ui/inbox/InboxWatcher.java
> [9773] Fix InboxWatcher if too many open files under Linux

- at.medevit.ch.artikelstamm.elexis.common/src/at/medevit/ch/artikelstamm/elexis/common/ui/cv/ArtikelstammCodeSelectorFactory.java
- at.medevit.ch.artikelstamm.elexis.common/src/at/medevit/ch/artikelstamm/elexis/common/ui/cv/BlackboxViewerFilterAction.java
- com.hilotec.elexis.kgview/src/com/hilotec/elexis/kgview/ArchivKG.java
cleanUp function to include checking & and  ' characters in kgview which was causing IllegalArgumentException in ArchivKG
> Bugfix com.hilotec.opendocument, Bugfix: ArchivKG IllegalArgumentException in cleanUp method, Illegal thread access bug

- bundles/ch.elexis.omnivore.data/src/ch/elexis/omnivore/data/DocHandle.java
- bundles/ch.novcom.elexis.mednet.plugin/META-INF/MANIFEST.MF
Fixed a misssing library in the mednet plugin  MANIFEST
Fixed a bug in the omnivore DocHandle introduced by the last modification
> Fixed two bugs

- bundles/at.medevit.elexis.ehc.ui/META-INF/MANIFEST.MF
- bundles/at.medevit.elexis.emediplan.ui/META-INF/MANIFEST.MF
- bundles/ch.docbox.elexis/META-INF/MANIFEST.MF
- bundles/ch.elexis.agenda/META-INF/MANIFEST.MF
- features/at.medevit.elexis.ehc.feature/feature.xml
- features/ch.docbox.elexis.feature/feature.xml
- features/ch.elexis.agenda.feature/feature.xml
> [14658] eMediplan needs fop wrapper (#157)

- bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/function/LoadEventsFunction.java
> [14902] Problem beim verschieben eines Termins aus der Agenda Web via

- bundles/ch.elexis.icpc.fire/src/ch/elexis/icpc/fire/handlers/ExportFireHandler.java
- bundles/ch.elexis.icpc.fire/src/ch/elexis/icpc/fire/ui/Preferences.java
core DateTimeFieldEditor ist voraussetzung bitte zuerst übernehmen
> [10716] Änderungswünsche FIRE - cfgparam

- bundles/ch.elexis.base.ch.migel/META-INF/MANIFEST.MF
- bundles/ch.elexis.base.ch.migel/src/ch/elexis/base/ch/migel/ui/MiGelImporter.java
Eigentlich müsste noch ein Unit-Test dafür her.
Bin aber nicht sicher, ob ich einen JUnit test oder einen PDE unit test erstellen soll und was besser wäre
> [#24376] Import Migel-XLSX for de, fr and it

- bundles/ch.itmed.fop.printing/src/ch/itmed/fop/printing/xml/documents/RecurringAppointmentsCard.java
added mandator element for ReccurringAppointmentsCard
> [24500] Added mandator element

- bundles/ch.elexis.pdfBills/rsc/44_patbill.xsl
- bundles/ch.elexis.pdfBills/rsc/44_patbill_m1.xsl
- bundles/ch.elexis.pdfBills/rsc/44_patbill_m2.xsl
- bundles/ch.elexis.pdfBills/rsc/44_patbill_m3.xsl
- bundles/ch.elexis.pdfBills/rsc/45_patbill.xsl
- bundles/ch.elexis.pdfBills/rsc/45_patbill_m1.xsl
- bundles/ch.elexis.pdfBills/rsc/45_patbill_m2.xsl
- bundles/ch.elexis.pdfBills/rsc/45_patbill_m3.xsl
- bundles/ch.elexis.pdfBills/rsc/45_qr_patbill.xsl
- bundles/ch.elexis.pdfBills/rsc/45_qr_patbill_m1.xsl
- bundles/ch.elexis.pdfBills/rsc/45_qr_patbill_m2.xsl
- bundles/ch.elexis.pdfBills/rsc/45_qr_patbill_m3.xsl
- bundles/ch.elexis.pdfBills/rsc/script/45_patbill_m1.xsl
- bundles/ch.elexis.pdfBills/rsc/script/45_patbill_m2.xsl
- bundles/ch.elexis.pdfBills/rsc/script/45_patbill_m3.xsl
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/ElexisPDFGenerator.java
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/PreferencePage.java
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/RnOutputter.java
Editable Textdialog for invoicetexts (the PR for the internationalized text is in the core Repository)
> [24420] Editable Textdialog for invoicetexts

- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/ElexisPDFGenerator.java
Beim Testen im Master habe ich gemerkt, dass wenn man die Mahnung-Stufen erhöht, hat sich der Text nicht geändert. Ich konnte es jetzt es so lösen
> 24699 textdialog mahnungen fix

- bundles/at.medevit.elexis.loinc/src/at/medevit/elexis/loinc/model/LoincCode.java
- bundles/ch.elexis.agenda/src/ch/elexis/agenda/data/TagesNachricht.java
- bundles/ch.elexis.agenda/src/ch/elexis/agenda/data/Termin.java
- bundles/ch.elexis.base.befunde/src/ch/elexis/befunde/Messwert.java
- bundles/ch.elexis.base.messages/src/ch/elexis/messages/Message.java
- bundles/ch.elexis.impfplan/src/ch/elexis/impfplan/model/VaccinationType.java
- bundles/ch.elexis.notes/src/ch/elexis/notes/Note.java
Only the easy part, removing unused code, not yet generating missing tables
> [24742] Remove obsolete create table statements

- bundles/ch.elexis.pdfBills.privat/rsc/44_patbill.xsl
- bundles/ch.elexis.pdfBills.privat/rsc/45_patbill.xsl
- bundles/ch.elexis.pdfBills.privat/rsc/45_qr_patbill.xsl
- bundles/ch.elexis.pdfBills.privat/src/ch/elexis/pdfBills/privat/ElexisPDFGenerator.java
- bundles/ch.elexis.pdfBills.privat/src/ch/elexis/pdfBills/privat/PrivatQrRnOutputter.java
- bundles/ch.elexis.pdfBills/rsc/44_patbill_m2.xsl
- bundles/ch.elexis.pdfBills/rsc/44_patbill_m3.xsl
- bundles/ch.elexis.pdfBills/rsc/45_patbill_m2.xsl
- bundles/ch.elexis.pdfBills/rsc/45_patbill_m3.xsl
- bundles/ch.elexis.pdfBills/rsc/45_qr_patbill_m2.xsl
- bundles/ch.elexis.pdfBills/rsc/45_qr_patbill_m3.xsl
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/ElexisPDFGenerator.java
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/PreferencePage.java
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/QrRnOutputter.java
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/RnOutputter.java
removed reminderdays_M2 and reminderdays_M3 because it is replaced with "invoice texts" (closed the last PR because there was a merge conflict)
> [24565] removed reminderdays_M2 and M3

- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/ElexisPDFGenerator.java
Default messages for Preference Page
> [25233] Added Default message for PreferencePage

- bundles/ch.elexis.pdfBills.privat/src/ch/elexis/pdfBills/privat/ElexisPDFGenerator.java
- bundles/ch.elexis.pdfBills/src/ch/elexis/pdfBills/ElexisPDFGenerator.java
Ich habe leider vergessen, die Änderungen auch im Projekt Folder ch.elexis.pdfBills.privat zu übernehmen
> [25233] qr beleg wird nicht korrket gedruckt

- bundles/at.medevit.elexis.documents.converter.ui/src/at/medevit/elexis/documents/converter/ui/preference/JodRestConverterPage.java
- bundles/at.medevit.elexis.documents.converter/src/at/medevit/elexis/documents/converter/JodRestDocumentConverter.java
providing default-value for URL in document converter
> [25464] JodConverter service, set default URL

- bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/SideBarComposite.java
- bundles/ch.elexis.kassenbuch/src/ch/elexis/buchhaltung/kassenbuch/KassenView.java
neue pull request mit formatter änderungen
> [25620] kassenbuch nach zahlen sortieren

- bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/Messages.java
- bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/SideBarComposite.java
habe die vorherigen codes angepasst
> [25624] Change title of web agenda

- bundles/ch.elexis.molemax/build.properties
Hier der Lib Ordner wurde referenziert
> [25513]Lib folder referenced Molemax

- bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/AppointmentDetailComposite.java
- bundles/ch.elexis.agenda/src/ch/elexis/agenda/data/Termin.java
> [25830] Differences in creating appointments between Agenda Web & Agenda large

- bundles/at.medevit.elexis.emediplan.core/src/at/medevit/elexis/emediplan/core/model/chmed16a/Patient.java
- bundles/ch.elexis.archie.patientstatistik/src/ch/elexis/archie/patientstatistik/VerrechnungsStatistikView.java
Hallo Thomas, 
bei Zeile 155 - 160 würde ich gerne eine andere Art und Weise finden um dies nicht so beizubehalten, ich weiss jedoch nicht genau wie ich das anstellen sollte, so das es immernoch die gleiche Ausgangslage erzielt (funktionierende sortierfunktion) , kannst du mir da bei einem kurzen Telefonat morgen irgendwann zwischen 10.45 -11:30 Uhr einen Tipp geben?
> 25848 sortierfunktion codesystem

- pom.xml
The same procedure as elexis-core
> Added mojo specs in parent pom to avoid warnings in the build process

- bundles/at.medevit.elexis.emediplan.core/src/at/medevit/elexis/emediplan/core/model/chmed16a/Patient.java
- bundles/ch.elexis.laborimport.medics.v2/src/ch/elexis/laborimport/medics/v2/Messages.java
- bundles/ch.elexis.laborimport.medics.v2/src/ch/elexis/laborimport/medics/v2/messages.properties
- bundles/ch.elexis.laborimport.medics.v2/src/ch/elexis/laborimport/medics/v2/messages_de.properties
- bundles/ch.elexis.laborimport.medics.v2/src/ch/elexis/laborimport/medics/v2/messages_en.properties
- bundles/ch.elexis.laborimport.medics.v2/src/ch/elexis/laborimport/medics/v2/messages_fr.properties
- bundles/ch.elexis.laborimport.medics.v2/src/ch/elexis/laborimport/medics/v2/messages_it.properties
- bundles/ch.elexis.labororder.lg1/src/ch/elexis/labororder/lg1/messages/Messages.java
- bundles/ch.elexis.labororder.lg1/src/ch/elexis/labororder/lg1/messages/messages.properties
- bundles/ch.elexis.labororder.lg1/src/ch/elexis/labororder/lg1/messages/messages_de.properties
- bundles/ch.elexis.labororder.lg1/src/ch/elexis/labororder/lg1/messages/messages_en.properties
- bundles/ch.elexis.labororder.lg1/src/ch/elexis/labororder/lg1/messages/messages_fr.properties
- bundles/ch.elexis.labororder.lg1/src/ch/elexis/labororder/lg1/messages/messages_it.properties
as i couldn't change the title of the LG1 Labor Auftrag as it can't be defined by text, i changed it back to the mesages of v3.8 as I was told, but didn't adjusted the LG1 Title
> 26226 medics labor auftrag neu beschriften

- bundles/ch.elexis.labororder.lg1_medicalvalues/readme.md
- bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/LabOrderAction.java
- bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/model/Patient.java
- bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/model/exceptions/NoEncounterSelectedException.java
Wir mussten in den letzten Wochen noch einige Kleinigkeiten an der URL und den QueryParams anpassen.
Hier die Anpassungen im Plugin dazu.
> [26233] Update order intelligence URL for LG1_medicalvalues laborder plugin

- bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/LabOrderAction.java
- bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/model/Patient.java
All errors should be displayed to the user instead of only being silently logged.
Added some more data that needed to be transferred to the order entry.
> LG1 - medicalvalues OE Plugin - display error messages and send additional data

- bundles/ch.elexis.agenda/src/ch/elexis/actions/AgendaActions.java
So wird beim Löschen eines Termins ein Eintrag in Logs in der Datenbank geschrieben.
> [26542] Agenda & Agenda Gross DB-Logs-Eintrag bei Termin Löschen

- bundles/ch.framsteg.elexis.administration.covercard/src/ch/framsteg/elexis/covercard/views/SearchView.java
Incorrect annotation corrected
> Corrected wrong annotation

- bundles/ch.elexis.mednet.webapi.ui/OSGI-INF/ch.elexis.mednet.webapi.ui.preferences.MedNetWebPreferencePage.xml
- bundles/ch.elexis.mednet.webapi.ui/src/ch/elexis/mednet/webapi/ui/preferences/MedNetWebPreferencePage.java
- bundles/ch.elexis.mednet.webapi.ui/src/ch/elexis/mednet/webapi/ui/preferences/PreferenceInitializer.java
> [26810] PreferenceInitializer angepasst, dass er den Namen nicht

- bundles/ch.itmed.fop.printing.ui/src/ch/itmed/fop/printing/handlers/ArticleMedicationLabelsHandler.java
AlternativePrescription hinzugefügt
> [26811] ArticleMedicationLabelsHandler angepasst und

- bundles/ch.elexis.global_inbox.core/src/ch/elexis/global_inbox/core/handler/ImportOmnivore.java
- bundles/ch.elexis.global_inbox.core/src/ch/elexis/global_inbox/core/util/ImportOmnivoreInboxUtil.java
- bundles/ch.elexis.global_inbox/src/ch/elexis/global_inbox/PreferencesServer.java
> [26828] Logger hinzugefügt und Preferences Page angepasst auf die

- bundles/ch.itmed.fop.printing.ui/plugin.xml
- bundles/ch.itmed.fop.printing.ui/src/ch/itmed/fop/printing/handlers/RowaArticleMedicationLabelHandler.java
- bundles/ch.itmed.fop.printing/res/xsl/RowaArticleMedicationLabel.xsl
- bundles/ch.itmed.fop.printing/src/ch/itmed/fop/printing/barcode/BarcodeCreator.java
- bundles/ch.itmed.fop.printing/src/ch/itmed/fop/printing/preferences/PreferenceConstants.java
- bundles/ch.itmed.fop.printing/src/ch/itmed/fop/printing/resources/Messages.java
- bundles/ch.itmed.fop.printing/src/ch/itmed/fop/printing/xml/documents/RowaArticleMedicationLabel.java
- bundles/ch.itmed.fop.printing/src/ch/itmed/fop/printing/xml/elements/RowaArticleMedicationElement.java
**gehört zu:** https://github.com/elexis/elexis-3-core/pull/828
> [26834] create article label for rowa output

- bundles/ch.elexis.agenda/src/ch/elexis/agenda/composite/AppointmentDetailComposite.java
> [27303] onContextDateSelected angepasst, um richtigen Termin zu

- bundles/ch.elexis.agenda/src/ch/elexis/agenda/views/AgendaGross.java
- bundles/ch.elexis.agenda/src/ch/elexis/agenda/views/BaseAgendaView.java
- bundles/ch.elexis.agenda/src/ch/elexis/agenda/views/TagesView.java
> [27326] TagesView hört auf DATE_CHANGED und aktualisiert die UI mit

- bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/ParallelComposite.java
- bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/WeekComposite.java
- bundles/ch.elexis.agenda/src/ch/elexis/actions/AgendaActions.java
- bundles/ch.elexis.agenda/src/ch/elexis/agenda/commands/DeleteHandler.java
- bundles/ch.elexis.agenda/src/ch/elexis/agenda/views/BaseAgendaView.java
Parallel-/Wochenansichten AgendaGross
> [27377] korrekten ContextService-Synchronisierung für

- bundles/ch.elexis.agenda/src/ch/elexis/agenda/views/BaseAgendaView.java
> [27377]  Aktualisiere ContextService und ESelectionService auch bei
